# Just run make in the repo of this file
all: createObject.exe

createObject.exe: createObject.cpp
	      gcc -g -Wall -o createObject createObject.cpp SimpleObject.cpp

clean:
	rm createObject.o createObject.exe