# Just run make in the repo of this file
all: binaryPatchIf.exe

binaryPatchIf.exe: binaryPatchIf.cpp
	      gcc -g -Wall -o binaryPatchIf binaryPatchIf.cpp

clean:
	rm binaryPatchIf.o binaryPatchIf.exe